### ISSUE TITLE
add support for ubuntu 20.04

### ISSUE THREAD

**Issue by richardforth** [richardforth/apache2buddy#331]
Reminder to add support for ubuntu 20.04

**Comment by richardforth** [comment]
docker image built but currently failing


```bash
# docker run --cap-add SYS_PTRACE forric/ubuntu_2004_apache2buddy_mas
 * Starting Apache httpd web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
 *
#################################################
apache2buddy.pl report for 829e332e03c8 (x.x.x.x)
#################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ @@ ] Unable to locate the PHP binary. PHP specific checks will be skipped.
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'dist'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distro'
[ !! ] Unable to locate the 'python2' binary.
[ !! ] Python scripting failed. Python requires package 'distro' or 'platform' to determine the Operating System and Version.
[root@perldev ubuntu_2004_apache2buddy_mas]#
```

**Comment by richardforth** [comment]
```bash
# docker run --cap-add SYS_PTRACE forric/ubuntu_2004_apache2buddy_stag
 * Starting Apache httpd web server apache2
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
 *
#####################################################
apache2buddy.pl report for 0a84f973fae2 (31.48.76.58)
#####################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ @@ ] Unable to locate the PHP binary. PHP specific checks will be skipped.
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'dist'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'distro'
[ !! ] Unable to locate the 'python2' binary.
[ !! ] Python scripting failed. Python requires package 'distro' or 'platform' to determine the Operating System and Version.
[root@perldev ubuntu_2004_apache2buddy_stag]#

```

**Comment by richardforth** [comment]
Here is the code that does that


```perl
       # Check for python (new in Debian 9 as it doesnt come with it out of the box)
        my $py_exists = 0;
        for my $pyname ( qw / python python3 python2 / ) {
                my $python = `which $pyname`;
                chomp( $python );
                unless ( $python ) {
                        show_crit_box(); 
                        print "Unable to locate the '$pyname' binary.\n";
                        next;
                }

                $py_exists = 1;
                if ( ! $NOOK ) { show_ok_box(); print "The '$pyname' binary exists and is available for use: ${CYAN}$python${ENDC}\n" }

                print "VERBOSE: Check OS platform\n" if $VERBOSE;

                for my $pyscript (@py_scripts) {
                        print "VERBOSE:   $python -c '$pyscript'\n" if $VERBOSE;
                        my $raw_platform = `$python -c \"$pyscript\"`;
                        # ('CentOS Linux', '7.3.1611', 'Core')
                        chomp($raw_platform);
                        next unless $raw_platform;

                        $raw_platform =~ s/[()']//g;
                        my ( $distro, $version, $codename ) = split( '\s*,\s+', $raw_platform);
                        next unless $distro;

                        @main::os_platform = ( $distro, $version, $codename );
                        return ( $distro, $version, $codename );
                }

        }
```

**Comment by richardforth** [comment]
full subroutine:

```perl
sub get_os_platform {

        return @main::os_platform if @main::os_platform; # we already know everything

         my @py_scripts = (
                # platform.linux_distribution() - This function is deprecated since Python 3.5
                # and removed in Python 3.8. See alternative like the distro package.
                'import platform; print(platform.linux_distribution())',
                # platform.dist() -  Deprecated since version 2.6.
                'import platform; print(platform.dist())',
                # distro.linux_distribution() - 'distro' is not default installed package
                'import distro; print(distro.linux_distribution())',
        );

        # Check for python (new in Debian 9 as it doesnt come with it out of the box)
        my $py_exists = 0;
        for my $pyname ( qw / python python3 python2 / ) {
                my $python = `which $pyname`;
                chomp( $python );
                unless ( $python ) {
                        show_crit_box(); 
                        print "Unable to locate the '$pyname' binary.\n";
                        next;
                }

                $py_exists = 1;
                if ( ! $NOOK ) { show_ok_box(); print "The '$pyname' binary exists and is available for use: ${CYAN}$python${ENDC}\n" }

                print "VERBOSE: Check OS platform\n" if $VERBOSE;

                for my $pyscript (@py_scripts) {
                        print "VERBOSE:   $python -c '$pyscript'\n" if $VERBOSE;
                        my $raw_platform = `$python -c \"$pyscript\"`;
                        # ('CentOS Linux', '7.3.1611', 'Core')
                        chomp($raw_platform);
                        next unless $raw_platform;

                        $raw_platform =~ s/[()']//g;
                        my ( $distro, $version, $codename ) = split( '\s*,\s+', $raw_platform);
                        next unless $distro;

                        @main::os_platform = ( $distro, $version, $codename );
                        return ( $distro, $version, $codename );
                }

        }

        # we can't determine OS and Version
        if ( $py_exists ) {
                show_crit_box(); print "Python scripting failed. Python requires package 'distro' or 'platform' to determine the Operating System and Version.\n";
        } else {
                show_crit_box(); print "Unable to locate the any 'python' binary. This script requires python to determine the Operating System and Version.\n";
                show_info_box(); print "${YELLOW}To fix this make sure the python2 or python3 package is installed.${ENDC}\n";
        }
        exit;

        # XXX instead of calling exit() we can:
        # @main::os_platform = ( 'Unknown Distro', '0.0', '' );
        # return @main::os_platform;
}
```

**Comment by richardforth** [comment]
ipython3 session

```python
----> 1 import distro

ModuleNotFoundError: No module named 'distro'

In [2]: import platform

In [3]: print(platform.dist())
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-78ef4a1618da> in <module>
----> 1 print(platform.dist())

AttributeError: module 'platform' has no attribute 'dist'

In [4]: print(platform.platform())
Linux-3.10.0-1127.10.1.el7.x86_64-x86_64-with-glibc2.29

In [5]: print(platform.release())
3.10.0-1127.10.1.el7.x86_64

In [6]: print(platform.os())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-edf91bf729c1> in <module>
----> 1 print(platform.os())

TypeError: 'module' object is not callable

In [7]: print(platform.version)
<function version at 0x7f3ed4ab5670>

In [8]: print(platform.system())
Linux

In [9]: print(platform.os())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-edf91bf729c1> in <module>
----> 1 print(platform.os())

TypeError: 'module' object is not callable

In [10]: print(platform.os)
<module 'os' from '/usr/lib/python3.8/os.py'>

In [11]: print(platform.architecture())
('64bit', 'ELF')

In [12]: print(platform.architecture
   architecture()          mac_ver()               platform()              python_compiler()       python_version_tuple()  system()                version()
   collections             machine()               processor()             python_implementation() re                      system_alias()          win32_edition()
   java_ver()              node()                  python_branch()         python_revision()       release()               uname()                 win32_is_iot()
   libc_ver()              os                      python_build()          python_version()        sys                     uname_result            win32_ver()
   function(executable='/usr/bin/python3', bits='', linkage='')
```

**Comment by richardforth** [comment]
my @py_scripts = (
                # platform.linux_distribution() - This function is deprecated since Python 3.5
                # and removed in Python 3.8. See alternative like the distro package.
                'import platform; print(platform.linux_distribution())',
                # platform.dist() -  Deprecated since version 2.6.
                'import platform; print(platform.dist())',
                # distro.linux_distribution() - 'distro' is not default installed package
                'import distro; print(distro.linux_distribution())',
        );

need to work out what works with ubuntu 20.04 and add it to this array

**Comment by richardforth** [comment]
needed ab extra package installing

```bash
# apt-get install python3-distro
```

```bash
root@2d61c9158864:/# service apache2 start && curl -sk https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl
 * Starting Apache httpd web server apache2                                                                                                                                   *
#####################################################
apache2buddy.pl report for 2d61c9158864 (31.48.76.58)
#####################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ @@ ] Unable to locate the PHP binary. PHP specific checks will be skipped.
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'dist'
[ -- ] Distro: Ubuntu
[ -- ] Version: 20.04
[ -- ] Codename: focal
[ OK ] This distro is supported by apache2buddy.pl.
[ !! ] This distro version (20.04) is not supported by apache2buddy.pl.
[ @@ ] Supported Ubuntu (LTS ONLY) versions: '16.04', '18.04'. To run anyway (at your own risk), try -O or --skip-os-version-check.
```

**Comment by richardforth** [comment]
looks liek its all working, I just need to gracefull handle these:

```bash
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'dist'
```

**Comment by richardforth** [comment]
TODO List:

1. Gracefully recommend python3-dist installation
2, Gracefuly handle the tracebacks

**Comment by richardforth** [comment]
```bash
root@10b463f6d227:/# apt-get install python3-distro
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  distro-info-data lsb-release
The following NEW packages will be installed:
  distro-info-data lsb-release python3-distro
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
Need to get 29.8 kB of archives.
After this operation, 156 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 distro-info-data all 0.43ubuntu1.1 [4584 B]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 lsb-release all 11.1.0ubuntu2 [10.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-distro all 1.4.0-1 [14.6 kB]
Fetched 29.8 kB in 0s (101 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package distro-info-data.
(Reading database ... 10143 files and directories currently installed.)
Preparing to unpack .../distro-info-data_0.43ubuntu1.1_all.deb ...
Unpacking distro-info-data (0.43ubuntu1.1) ...
Selecting previously unselected package lsb-release.
Preparing to unpack .../lsb-release_11.1.0ubuntu2_all.deb ...
Unpacking lsb-release (11.1.0ubuntu2) ...
Selecting previously unselected package python3-distro.
Preparing to unpack .../python3-distro_1.4.0-1_all.deb ...
Unpacking python3-distro (1.4.0-1) ...
Setting up distro-info-data (0.43ubuntu1.1) ...
Setting up lsb-release (11.1.0ubuntu2) ...
Setting up python3-distro (1.4.0-1) ...
root@10b463f6d227:/# service apache2 start && curl -sk https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl - --skip-os-version-check
 * Starting Apache httpd web server apache2                                                                                                                                   *
#####################################################
apache2buddy.pl report for 10b463f6d227 (31.48.76.58)
#####################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ @@ ] Unable to locate the PHP binary. PHP specific checks will be skipped.
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'linux_distribution'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'platform' has no attribute 'dist'
[ -- ] Distro: Ubuntu
[ -- ] Version: 20.04
[ -- ] Codename: focal
[ >> ] OS Version Checks were skipped by user directive, you may get errors.
[ -- ] Hostname: 10b463f6d227
[ -- ] Primary IP: x.x.x.x
[ -- ] We are checking the service running on port 80...
[ -- ] The process listening on port 80 is /usr/sbin/apache2
[ -- ] The process running on port 80 is Apache/2.4.41 (Ubuntu).
[ -- ] The full path to the Apache config file is: /etc/apache2/apache2.conf
[ -- ] Apache is using event model.
[ -- ] pidfile setting is /var/run/apache2$SUFFIX/apache2.pid.
[ -- ] Actual pidfile is /var/run/apache2/apache2.pid.
[ -- ] Parent PID: 38.
[ OK ] Memory usage of parent PID is less than 50MB: 1280 Kilobytes.
[ -- ] Apache has been running 0d 0h 00m 44s.
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.
[ -- ] Your server has 990 MB of PHYSICAL memory.
[ >> ] ServerLimit directive not found, assuming default values.
[ -- ] Your ServerLimit setting is 16.
[ -- ] Your ThreadsPerChild setting is 25.
[ -- ] Your ThreadsPerChild setting for worker MPM is  25
[ -- ] Your ServerLimit setting for worker MPM is  16
[ -- ] Your MaxRequestWorkers setting is 150.
[ OK ] Current Apache Process Count is 3, including the parent PID.
[ -- ] Number of vhosts detected: 0.
[ OK ] Current Apache vHost Count is less than maxrequestworkers.
[ @@ ] vHost Count works only when we have NameVirtualHosting enabled, check config manually, they may only have the default vhost.
[ -- ] This server is NOT running Plesk.
[ -- ] This server is NOT running cPanel.
[ -- ] This server is NOT running Virtualmin.
[ OK ] No additional services were detected.
[ OK ] No large log files were found in /var/log/apache2.
[ OK ] MaxClients has not been hit recently.
[ >> ] Apache only logs maxclients/maxrequestworkers hits once in a lifetime, if no restart has happened this event may have been rotated away.
[ >> ] As a backup check, please compare number of running apache processes (minus 1 for parent) against maxclients/maxrequestworkers.
[ >> ] For more information see https://github.com/apache/httpd/blob/0b61edca6cdda2737aa1d84a4526c5f9d2e23a8c/server/mpm/prefork/prefork.c#L809
[ OK ] No package updates found.
[ -- ] apache2 is currently using 11.59 MB of memory.


--------------------------------------------------------------------------------
### GENERAL FINDINGS & RECOMMENDATIONS ###
--------------------------------------------------------------------------------
Apache2buddy.pl report for server: 10b463f6d227 (x.x.x.x):

Settings considered for this report:
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.

        Your server's physical RAM:                                   990 MB
        Remaining Memory after other services considered:             990 MB
        Apache's MaxRequestWorkers directive:                         150      <--------- Current Setting
        Apache MPM Model:                                             event
        Largest Apache process (by memory):                           218 MB
        Apache appears to be running in event mode.
        Please check manually for backend processes such as PHP-FPM and pm.max_children.
        Apache2buddy does not calculate maxclients for worker model.
--------------------------------------------------------------------------------
A log file entry has been made in: /var/log/apache2buddy.log for future reference.

Last 5 entries:

2020/06/18 21:00:40 Uptime: "0d 0h 00m 44s"  Model: "Event" Memory: "990 MB" Maxclients: "150" Recommended: "N\A" Smallest: "218.49 MB" Avg: "218.49 MB" Largest: "218.49 MB"

root@10b463f6d227:/#
```

**Comment by richardforth** [comment]
Hacked about on an ubuntu VM and got the python dist thing to act more gracefully:

```bash
root@ubu2004:~# vim apache2buddy.pl
root@ubu2004:~# perl apache2buddy.pl
###################################################
apache2buddy.pl report for ubu2004 (192.237.179.95)
###################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ @@ ] Unable to locate the PHP binary. PHP specific checks will be skipped.
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
[ -- ] Distro: Ubuntu
[ -- ] Version: 20.04
[ -- ] Codename: focal
[ OK ] This distro is supported by apache2buddy.pl.
[ !! ] This distro version (20.04) is not supported by apache2buddy.pl.
[ @@ ] Supported Ubuntu (LTS ONLY) versions: '16.04', '18.04'. To run anyway (at your own risk), try -O or --skip-os-version-check.
```

without python3-distro installed

```bash
root@ubu2004:~# perl apache2buddy.pl
###################################################
apache2buddy.pl report for ubu2004 (192.237.179.95)
###################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ @@ ] Unable to locate the PHP binary. PHP specific checks will be skipped.
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
[ !! ] Unable to locate the 'python2' binary.
[ !! ] Python scripting failed. Python requires package 'distro' or 'platform' to determine the Operating System and Version.
root@ubu2004:~#
```

code changed:

from:
```perl
         my @py_scripts = (
                # platform.linux_distribution() - This function is deprecated since Python 3.5
                # and removed in Python 3.8. See alternative like the distro package.
                'import platform; print(platform.linux_distribution())',
                # platform.dist() -  Deprecated since version 2.6.
                'import platform; print(platform.dist())',
                # distro.linux_distribution() - 'distro' is not default installed package
                'import distro; print(distro.linux_distribution())',
        );

```


to

```perl
         my @py_scripts = (
                # platform.linux_distribution() - This function is deprecated since Python 3.5
                # and removed in Python 3.8. See alternative like the distro package.
                "try:
        import platform
        print(platform.linux_distribution())
except AttributeError as e:
    pass",
                # platform.dist() -  Deprecated since version 2.6.
                "try:
        import platform
        print(platform.dist())
except AttributeError as e:
    pass",
                # distro.linux_distribution() - 'distro' is not default installed package
                "try:
        import distro
        print(distro.linux_distribution())
except AttributeError as e:
    pass
except ModuleNotFoundError as e:
    pass",
        ); # Note the pass is required because perl needs an empty result for error handling internally switching from python back to perl.
           # We just want python to die quietly in a corner for aestehetic reasons.
```

the odd nesting is due to the python scripts now being multiline perl strings, and in python, spacing MATTERS.

Will update staging code.

**Comment by richardforth** [comment]
staging seems to work

```bash
root@ubu2004:~# curl -sk https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl - --skip-os-version-check
############################################
apache2buddy.pl report for ubu2004 (x.x.x.x)
############################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ @@ ] Unable to locate the PHP binary. PHP specific checks will be skipped.
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
[ !! ] Unable to locate the 'python2' binary.
[ !! ] Python scripting failed. Python requires package 'distro' or 'platform' to determine the Operating System and Version.
root@ubu2004:~# apt install python3-distro
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  apport-symptoms python3-entrypoints python3-httplib2 python3-keyring python3-lazr.uri python3-problem-report python3-pyxs python3-secretstorage python3-simplejson
  python3-systemd python3-wadllib
Use 'apt autoremove' to remove them.
The following NEW packages will be installed:
  python3-distro
0 upgraded, 1 newly installed, 0 to remove and 69 not upgraded.
Need to get 14.6 kB of archives.
After this operation, 70.7 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/main amd64 python3-distro all 1.4.0-1 [14.6 kB]
Fetched 14.6 kB in 0s (49.0 kB/s)
Selecting previously unselected package python3-distro.
(Reading database ... 63810 files and directories currently installed.)
Preparing to unpack .../python3-distro_1.4.0-1_all.deb ...
Unpacking python3-distro (1.4.0-1) ...
Setting up python3-distro (1.4.0-1) ...
root@ubu2004:~# curl -sk https://raw.githubusercontent.com/richardforth/apache2buddy/staging/apache2buddy.pl | perl - --skip-os-version-check
###################################################
apache2buddy.pl report for ubu2004 (192.237.179.95)
###################################################
[ OK ] This script is being run as root.
[ OK ] The utility 'pmap' exists and is available for use: /usr/bin/pmap
[ OK ] The utility 'netstat' exists and is available for use: /usr/bin/netstat
[ @@ ] Unable to locate the PHP binary. PHP specific checks will be skipped.
[ OK ] The utility 'apachectl' exists and is available for use: /usr/sbin/apachectl
[ OK ] The port (port 80) is a valid port.
[ -- ] We are attempting to discover the operating system type and version number ...
[ !! ] Unable to locate the 'python' binary.
[ OK ] The 'python3' binary exists and is available for use: /usr/bin/python3
[ -- ] Distro: Ubuntu
[ -- ] Version: 20.04
[ -- ] Codename: focal
[ >> ] OS Version Checks were skipped by user directive, you may get errors.
[ -- ] Hostname: ubu2004
[ -- ] Primary IP: x.x.x.x
[ -- ] We are checking the service running on port 80...
[ -- ] The process listening on port 80 is /usr/sbin/apache2
[ -- ] The process running on port 80 is Apache/2.4.41 (Ubuntu).
[ -- ] The full path to the Apache config file is: /etc/apache2/apache2.conf
[ -- ] Apache is using event model.
[ -- ] pidfile setting is /var/run/apache2$SUFFIX/apache2.pid.
[ -- ] Actual pidfile is /var/run/apache2/apache2.pid.
[ -- ] Parent PID: 5001.
[ OK ] Memory usage of parent PID is less than 50MB: 1296 Kilobytes.
[ -- ] Apache has been running 0d 01h 02m 16s.
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.
[ -- ] Your server has 471 MB of PHYSICAL memory.
[ >> ] ServerLimit directive not found, assuming default values.
[ -- ] Your ServerLimit setting is 16.
[ -- ] Your ThreadsPerChild setting is 25.
[ -- ] Your ThreadsPerChild setting for worker MPM is  25
[ -- ] Your ServerLimit setting for worker MPM is  16
[ -- ] Your MaxRequestWorkers setting is 150.
[ OK ] Current Apache Process Count is 3, including the parent PID.
[ -- ] Number of vhosts detected: 0.
[ OK ] Current Apache vHost Count is less than maxrequestworkers.
[ @@ ] vHost Count works only when we have NameVirtualHosting enabled, check config manually, they may only have the default vhost.
[ -- ] This server is NOT running Plesk.
[ -- ] This server is NOT running cPanel.
[ -- ] This server is NOT running Virtualmin.
[ OK ] No additional services were detected.
[ OK ] No large log files were found in /var/log/apache2.
[ OK ] MaxClients has not been hit recently.
[ >> ] Apache only logs maxclients/maxrequestworkers hits once in a lifetime, if no restart has happened this event may have been rotated away.
[ >> ] As a backup check, please compare number of running apache processes (minus 1 for parent) against maxclients/maxrequestworkers.
[ >> ] For more information see https://github.com/apache/httpd/blob/0b61edca6cdda2737aa1d84a4526c5f9d2e23a8c/server/mpm/prefork/prefork.c#L809
[ OK ] No package updates found.
[ -- ] apache2 is currently using 10.91 MB of memory.


--------------------------------------------------------------------------------
### GENERAL FINDINGS & RECOMMENDATIONS ###
--------------------------------------------------------------------------------
Apache2buddy.pl report for server: ubu2004 (x.x.x.x):

Settings considered for this report:
[ !! ] *** LOW UPTIME ***.
[ @@ ] The following recommendations may be misleading - apache has been restarted within the last 24 hours.

        Your server's physical RAM:                                   471 MB
        Remaining Memory after other services considered:             471 MB
        Apache's MaxRequestWorkers directive:                         150      <--------- Current Setting
        Apache MPM Model:                                             event
        Largest Apache process (by memory):                           218 MB
        Apache appears to be running in event mode.
        Please check manually for backend processes such as PHP-FPM and pm.max_children.
        Apache2buddy does not calculate maxclients for worker model.
--------------------------------------------------------------------------------
A log file entry has been made in: /var/log/apache2buddy.log for future reference.

Last 5 entries:

2020/06/19 08:39:03 Uptime: "0d 01h 02m 16s"  Model: "Event" Memory: "471 MB" Maxclients: "150" Recommended: "N\A" Smallest: "218.52 MB" Avg: "218.54 MB" Largest: "218.57 MB"

root@ubu2004:~#
```

Will test more later and add official support shortly

**Comment by richardforth** [comment]
Closed
